### ISSUE TITLE
contact nn'existe pas

### ISSUE THREAD

**Issue by juliengrima** [WildCodeSchool/bleau_S2_2016_haras_metamorphose#14]
http://localhost/bleau_S2_2016_haras_metamorphose/web/app_dev.php/contact

Variable "contactAddress" does not exist in @Haras/contact.html.twig at line 63.

**Comment by juliengrima** [comment]
$pages = $em->getRepository('HarasBundle:Page')->findById([14, 15, $page->getId()]);

**Comment by cyril-lemaire** [comment]
C'est simplement qu'on a renommé le text contact (ou contactName je sais plus) en contactAddress pour plus de clarté. Il faut recharger la bdd ou renommer physiquement le texte en contactAddress pour résoudre le bug.
